version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - url-shortener-network

  server:
    build: .
    container_name: server
    restart: always
    env_file:
      - .env
    ports:
      - 3005:3005
    depends_on:
      - redis
    networks:
      - url-shortener-network
networks:
  url-shortener-network:
    driver: bridge
